Repository Andruha99/lesson5, pull requests merged in 2022-11, with the labels that each got.

#1 try work on github
  CSS/style1.css
  images/man.png
  index/index.html
Labels: help wanted

#2 init(index)
  index/index.html
Labels: good first issue

#6 little fix
  index/index.html
Labels: good first issue

#7 fixed sttyle of footer
  CSS/footer.css
  index/index.html
Labels: documentation
